# pretty much copy and paste from Travis docs
# testing on three versions only to be considerate with their servers
language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
# install: "pip install -r requirements.txt"
# command to run tests
script: nosetests